on:
    push: 
        branches:
            - main 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3  
              with: 
                username: ${{secrets.DOCKER_USER_NAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5  
              with:
                context: .
                push: true
                tags: ${{secrets.DOCKER_USER_NAME}}/bankhub
            - name: Dockerhub 
              run: docker logout  
    deploy:
        needs: build
        runs-on: self-hosted

        steps:
          - name: Pull Docker image
            run: sudo docker pull ${{secrets.DOCKER_USER_NAME}}/bankhub:latest
          - name: Delete old docker containers
            run: sudo docker rm -f bank-hub|| true
            
          - name: Run Docker container
            run: sudo docker run -d -p 80:80 --name bank-hub ${{secrets.DOCKER_USER_NAME}}/bankhub:latest
           
          